import type { EvolutionRule } from "./evolutions";

// Paldea/Hisui routes supplement the legacy evolution catalog. Normal level-up
// chains use the same time scale already adopted by the PokéRole sheets.
export const PALDEA_HISUI_EVOLUTION_RULES: EvolutionRule[] = [
  // Hisui regional chains and new evolutions.
  {
    from: "Voltorb (Hisuian Form)",
    to: "Electrode (Hisuian Form)",
    kinds: ["item"],
    items: ["Leaf Stone"],
  },
  {
    from: "Growlithe (Hisuian Form)",
    to: "Arcanine (Hisuian Form)",
    kinds: ["item"],
    items: ["Fire Stone"],
  },
  {
    from: "Quilava",
    to: "Typhlosion (Hisuian Form)",
    kinds: ["time", "specific"],
    time: "medium",
    specific: "Evoluir na região de Hisui",
  },
  {
    from: "Dewott",
    to: "Samurott (Hisuian Form)",
    kinds: ["time", "specific"],
    time: "medium",
    specific: "Evoluir na região de Hisui",
  },
  {
    from: "Dartrix",
    to: "Decidueye (Hisuian Form)",
    kinds: ["time", "specific"],
    time: "medium",
    specific: "Evoluir na região de Hisui",
  },
  {
    from: "Petilil",
    to: "Lilligant (Hisuian Form)",
    kinds: ["item", "specific"],
    items: ["Sun Stone"],
    specific: "Usar a pedra na região de Hisui",
  },
  {
    from: "Goomy",
    to: "Sliggoo (Hisuian Form)",
    kinds: ["time", "specific"],
    time: "medium",
    specific: "Evoluir na região de Hisui",
  },
  {
    from: "Sliggoo (Hisuian Form)",
    to: "Goodra (Hisuian Form)",
    kinds: ["time", "specific"],
    time: "medium",
    specific: "Evoluir durante chuva ou neblina",
  },
  {
    from: "Zorua (Hisuian Form)",
    to: "Zoroark (Hisuian Form)",
    kinds: ["time"],
    time: "medium",
  },
  {
    from: "Rufflet",
    to: "Braviary (Hisuian Form)",
    kinds: ["time", "specific"],
    time: "slow",
    specific: "Evoluir na região de Hisui",
  },
  {
    from: "Bergmite",
    to: "Avalugg (Hisuian Form)",
    kinds: ["time", "specific"],
    time: "slow",
    specific: "Evoluir na região de Hisui",
  },
  {
    from: "Qwilfish (Hisuian Form)",
    to: "Overqwil",
    kinds: ["specific"],
    specific: "Usar Barb Barrage em Strong Style 20 vezes",
  },
  {
    from: "Qwilfish (Hisuian Form)",
    to: "Overqwil",
    kinds: ["specific"],
    specific: "Alternativa: evoluir conhecendo Barb Barrage",
  },
  {
    from: "Sneasel (Hisuian Form)",
    to: "Sneasler",
    kinds: ["item", "specific"],
    items: ["Razor Claw"],
    specific: "Usar durante o dia",
  },
  {
    from: "Stantler",
    to: "Wyrdeer",
    kinds: ["specific"],
    specific: "Usar Psyshield Bash em Agile Style 20 vezes",
  },
  {
    from: "Scyther",
    to: "Kleavor",
    kinds: ["item"],
    items: ["Black Augurite"],
  },
  {
    from: "Ursaring",
    to: "Ursaluna",
    kinds: ["item", "specific"],
    items: ["Peat Block"],
    specific: "Usar durante uma Lua Cheia",
  },
  {
    from: "Basculin (White-Striped Form)",
    to: "Basculegion",
    kinds: ["specific"],
    specific: "Receber 294 pontos de dano de recuo acumulado sem desmaiar",
  },

  // Paldea standard level-up chains.
  { from: "Sprigatito", to: "Floragato", kinds: ["time"], time: "medium" },
  { from: "Floragato", to: "Meowscarada", kinds: ["time"], time: "medium" },
  { from: "Fuecoco", to: "Crocalor", kinds: ["time"], time: "medium" },
  { from: "Crocalor", to: "Skeledirge", kinds: ["time"], time: "medium" },
  { from: "Quaxly", to: "Quaxwell", kinds: ["time"], time: "medium" },
  { from: "Quaxwell", to: "Quaquaval", kinds: ["time"], time: "medium" },
  { from: "Lechonk", to: "Oinkologne", kinds: ["time"], time: "medium" },
  { from: "Tarountula", to: "Spidops", kinds: ["time"], time: "fast" },
  { from: "Nymble", to: "Lokix", kinds: ["time"], time: "fast" },
  { from: "Pawmi", to: "Pawmo", kinds: ["time"], time: "medium" },
  {
    from: "Pawmo",
    to: "Pawmot",
    kinds: ["time", "specific"],
    time: "medium",
    specific: "Caminhar 1.000 passos fora da Poké Bola de uma vez",
  },
  {
    from: "Tandemaus",
    to: "Maushold",
    kinds: ["time", "specific"],
    time: "medium",
    specific: "A forma Family of Three é rara e determinada aleatoriamente",
  },
  { from: "Fidough", to: "Dachsbun", kinds: ["time"], time: "medium" },
  { from: "Smoliv", to: "Dolliv", kinds: ["time"], time: "medium" },
  { from: "Dolliv", to: "Arboliva", kinds: ["time"], time: "medium" },
  { from: "Nacli", to: "Naclstack", kinds: ["time"], time: "medium" },
  { from: "Naclstack", to: "Garganacl", kinds: ["time"], time: "medium" },
  {
    from: "Charcadet",
    to: "Armarouge",
    kinds: ["item"],
    items: ["Auspicious Armor"],
  },
  {
    from: "Charcadet",
    to: "Ceruledge",
    kinds: ["item"],
    items: ["Malicious Armor"],
  },
  { from: "Tadbulb", to: "Bellibolt", kinds: ["item"], items: ["Thunder Stone"] },
  { from: "Wattrel", to: "Kilowattrel", kinds: ["time"], time: "medium" },
  { from: "Maschiff", to: "Mabosstiff", kinds: ["time"], time: "medium" },
  { from: "Shroodle", to: "Grafaiai", kinds: ["time"], time: "medium" },
  {
    from: "Bramblin",
    to: "Brambleghast",
    kinds: ["time", "specific"],
    time: "medium",
    specific: "Caminhar 1.000 passos fora da Poké Bola de uma vez",
  },
  { from: "Toedscool", to: "Toedscruel", kinds: ["time"], time: "medium" },
  { from: "Capsakid", to: "Scovillain", kinds: ["item"], items: ["Fire Stone"] },
  {
    from: "Rellor",
    to: "Rabsca",
    kinds: ["time", "specific"],
    time: "medium",
    specific: "Caminhar 1.000 passos fora da Poké Bola de uma vez",
  },
  { from: "Flittle", to: "Espathra", kinds: ["time"], time: "medium" },
  { from: "Tinkatink", to: "Tinkatuff", kinds: ["time"], time: "medium" },
  { from: "Tinkatuff", to: "Tinkaton", kinds: ["time"], time: "medium" },
  { from: "Wiglett", to: "Wugtrio", kinds: ["time"], time: "medium" },
  {
    from: "Finizen",
    to: "Palafin",
    kinds: ["time", "specific"],
    time: "medium",
    specific: "Evoluir enquanto joga com outros jogadores no Union Circle",
  },
  { from: "Varoom", to: "Revavroom", kinds: ["time"], time: "medium" },
  { from: "Glimmet", to: "Glimmora", kinds: ["time"], time: "medium" },
  {
    from: "Greavard",
    to: "Houndstone",
    kinds: ["time", "specific"],
    time: "medium",
    specific: "Evoluir durante a noite",
  },
  { from: "Cetoddle", to: "Cetitan", kinds: ["item"], items: ["Ice Stone"] },
  { from: "Frigibax", to: "Arctibax", kinds: ["time"], time: "slow" },
  { from: "Arctibax", to: "Baxcalibur", kinds: ["time"], time: "slow" },
  {
    from: "Gimmighoul",
    to: "Gholdengo",
    kinds: ["specific"],
    specific: "Juntar 999 Gimmighoul Coins e então evoluir",
  },

  // New branches from species that were already in the catalog.
  { from: "Wooper (Paldean Form)", to: "Clodsire", kinds: ["time"], time: "medium" },
  {
    from: "Primeape",
    to: "Annihilape",
    kinds: ["specific"],
    specific: "Usar Rage Fist 20 vezes e então evoluir",
  },
  {
    from: "Girafarig",
    to: "Farigiraf",
    kinds: ["specific"],
    specific: "Evoluir conhecendo Twin Beam",
  },
  {
    from: "Dunsparce",
    to: "Dudunsparce",
    kinds: ["specific"],
    specific: "Evoluir conhecendo Hyper Drill",
  },
  {
    from: "Bisharp",
    to: "Kingambit",
    kinds: ["specific"],
    specific: "Derrotar três Bisharp que carreguem Leader's Crest e então evoluir",
  },

  // Alternative methods documented for Scarlet/Violet and Legends: Arceus.
  { from: "Crabrawler", to: "Crabominable", kinds: ["item"], items: ["Ice Stone"] },
  { from: "Kadabra", to: "Alakazam", kinds: ["item"], items: ["Linking Cord"] },
  { from: "Machoke", to: "Machamp", kinds: ["item"], items: ["Linking Cord"] },
  { from: "Graveler", to: "Golem", kinds: ["item"], items: ["Linking Cord"] },
  { from: "Haunter", to: "Gengar", kinds: ["item"], items: ["Linking Cord"] },
  { from: "Nosepass", to: "Probopass", kinds: ["item"], items: ["Thunder Stone"] },
  {
    from: "Nosepass",
    to: "Probopass",
    kinds: ["specific"],
    specific: "Alternativa: evoluir em Coronet Highlands",
  },
];
