export const POKEMON_ABILITY_EFFECT_FALLBACKS: Record<string, string> = {
  "Anger Shell": "The first time this Pokemon falls to half its total HP or less, reduce its Defense and Sp. Defense by 1, then increase its Strength, Special and Dexterity by 1.",
  "Armor Tail": "This Pokemon and its allies cannot be targeted by Priority Moves used by foes.",
  "Beads of Ruin": "While this Pokemon is on the battlefield, reduce the Sp. Defense of every other Pokemon by 1.",
  Costar: "When this Pokemon enters battle, copy the current Attribute increases and reductions of one ally.",
  "Cud Chew": "When this Pokemon consumes a Berry, it receives that Berry's effect again at the end of the next Round.",
  "Earth Eater": "Ground-Type Moves do not damage this Pokemon. When it is hit by one, heal 1 HP instead.",
  Electromorphosis: "After this Pokemon takes damage from an attack, add 1 Extra Die to the next Electric-Type Damage Pool it rolls.",
  "Embody Aspect": "When this Pokemon assumes a masked Terastal Form, increase the Attribute tied to its mask by 1: Dexterity for Teal, Strength for Hearthflame, Insight for Wellspring or Vitality for Cornerstone.",
  "Good as Gold": "Support Moves used by other Pokemon do not affect this Pokemon. Field effects and this Pokemon's own Moves still work normally.",
  "Guard Dog": "This Pokemon cannot be forced to switch out. If Intimidate would reduce its Strength, increase its Strength by 1 instead.",
  "Hadron Engine": "When this Pokemon enters battle, it starts Electric Terrain. While Electric Terrain is active, increase its Special Attribute by 1.",
  Hospitality: "When this Pokemon enters battle, heal 1 HP from one ally in range.",
  "Lingering Aroma": "When a foe damages this Pokemon with a Contact Move, replace that foe's Ability with Lingering Aroma until the end of the scene.",
  "Mind's Eye": "This Pokemon's Accuracy cannot be reduced and it ignores increases to a foe's Evasion. Its Normal and Fighting-Type Moves can affect Ghost-Type targets.",
  "Mycelium Might": "This Pokemon's Support Moves act last in the Round, but ignore Abilities that would prevent or redirect their effects.",
  Opportunist: "Once per Round, when a foe increases an Attribute, increase the same Attribute of this Pokemon by 1.",
  "Orichalcum Pulse": "When this Pokemon enters battle, it starts Sunny Weather. While harsh sunlight is active, increase its Strength Attribute by 1.",
  "Poison Puppeteer": "Whenever a Move used by this Pokemon inflicts Poison, it also inflicts Confused on that target.",
  Protosynthesis: "During harsh sunlight, or after consuming Booster Energy, increase this Pokemon's highest Attribute by 1 for the rest of the scene.",
  "Purifying Salt": "This Pokemon is immune to Status Conditions and reduces damage from Ghost-Type Moves by 1.",
  "Quark Drive": "During Electric Terrain, or after consuming Booster Energy, increase this Pokemon's highest Attribute by 1 for the rest of the scene.",
  "Rocky Payload": "Add 1 Extra Die to the Damage Pool of Rock-Type Moves used by this Pokemon.",
  "Seed Sower": "The first time this Pokemon is damaged by an attack during a scene, it starts Grassy Terrain.",
  Sharpness: "Add 1 Die to the Damage Pool of slicing Moves used by this Pokemon.",
  "Supreme Overlord": "When this Pokemon enters battle, add 1 Die to its Damage Pools for each fainted ally in its party, up to 3 Dice.",
  "Supersweet Syrup": "The first time this Pokemon enters battle during a scene, reduce the Evasion of all foes in range by 1.",
  "Sword of Ruin": "While this Pokemon is on the battlefield, reduce the Defense of every other Pokemon by 1.",
  "Tablets of Ruin": "While this Pokemon is on the battlefield, reduce the Strength of every other Pokemon by 1.",
  "Tera Shift": "When this Pokemon enters battle, it immediately changes into its Terastal Form.",
  "Tera Shell": "While this Pokemon is at full HP, reduce damage from every Damaging Move that hits it by 1.",
  "Teraform Zero": "When this Pokemon changes into its Stellar Form, end all active Weather and Terrain effects.",
  "Toxic Chain": "After this Pokemon deals damage with a Move, roll 3 Chance Dice. If any die succeeds, inflict Poison on the target.",
  "Toxic Debris": "The first time this Pokemon takes damage from a Physical Move during a scene, scatter Toxic Spikes on the opposing side.",
  "Vessel of Ruin": "While this Pokemon is on the battlefield, reduce the Special Attribute of every other Pokemon by 1.",
  "Well-Baked Body": "Fire-Type Moves do not damage this Pokemon. The first time it is hit by one during a scene, increase its Defense by 2.",
  "Wind Power": "After this Pokemon is hit by a Wind Move, add 1 Extra Die to the next Electric-Type Damage Pool it rolls.",
  "Wind Rider": "Wind Moves do not damage this Pokemon. When Tailwind starts or a Wind Move targets it, increase its Strength by 1, up to 3 increases.",
  "Zero to Hero": "When this Pokemon switches out, change it into its Hero Form before it returns to battle.",
};

export function pokemonAbilityEffect(name: string, databaseEffect?: string | null): string {
  const stored = databaseEffect?.trim();
  return stored || POKEMON_ABILITY_EFFECT_FALLBACKS[name] || "";
}
