  -- D20 automated encounter engine foundation.
  -- Additive migration: it does not alter existing sheets, tokens or initiative rows.

  create table if not exists public.game_engine_sessions (
    id uuid primary key default gen_random_uuid(),
    game_id uuid not null unique references public.games(id) on delete cascade,
    page_id uuid references public.scenarios(id) on delete set null,
    system_id text not null default 'pokerole',
    status text not null default 'setup'
      check (status in ('setup', 'running', 'paused', 'finished')),
    version bigint not null default 0,
    state jsonb not null,
    created_by uuid not null references auth.users(id) on delete restrict,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint game_engine_state_is_object check (jsonb_typeof(state) = 'object')
  );

  create table if not exists public.game_engine_events (
    id bigint generated by default as identity primary key,
    session_id uuid not null references public.game_engine_sessions(id) on delete cascade,
    game_id uuid not null references public.games(id) on delete cascade,
    version bigint not null,
    actor_user_id uuid not null references auth.users(id) on delete restrict,
    command text not null,
    payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (session_id, version)
  );

  create index if not exists game_engine_events_session_version_idx
    on public.game_engine_events(session_id, version desc);
  create index if not exists game_engine_events_game_created_idx
    on public.game_engine_events(game_id, created_at desc);

  alter table public.game_engine_sessions enable row level security;
  alter table public.game_engine_events enable row level security;

  drop policy if exists "game members view engine sessions" on public.game_engine_sessions;
  create policy "game members view engine sessions"
    on public.game_engine_sessions for select to authenticated
    using (
      public.is_game_member(game_id, auth.uid())
      or public.is_game_narrator(game_id, auth.uid())
    );

  drop policy if exists "game members view engine events" on public.game_engine_events;
  create policy "game members view engine events"
    on public.game_engine_events for select to authenticated
    using (
      public.is_game_member(game_id, auth.uid())
      or public.is_game_narrator(game_id, auth.uid())
    );

  create or replace function public.start_game_engine_session(
    p_game_id uuid,
    p_page_id uuid,
    p_system_id text,
    p_state jsonb
  )
  returns public.game_engine_sessions
  language plpgsql
  security definer
  set search_path = public
  as $$
  declare
    v_user uuid := auth.uid();
    v_session public.game_engine_sessions;
  begin
    if v_user is null then
      raise exception 'Authentication required' using errcode = '42501';
    end if;
    if not public.is_game_narrator(p_game_id, v_user) then
      raise exception 'Only the game narrator can start an encounter' using errcode = '42501';
    end if;
    if jsonb_typeof(p_state) <> 'object'
       or coalesce((p_state ->> 'schemaVersion')::integer, 0) <> 1
       or jsonb_typeof(p_state -> 'participants') <> 'array' then
      raise exception 'Invalid engine state' using errcode = '22023';
    end if;
    if p_page_id is not null and not exists (
      select 1 from public.scenarios s where s.id = p_page_id and s.game_id = p_game_id
    ) then
      raise exception 'Page does not belong to this game' using errcode = '23503';
    end if;

    select * into v_session
    from public.game_engine_sessions
    where game_id = p_game_id
    for update;

    if found then
      delete from public.game_engine_events where session_id = v_session.id;
      update public.game_engine_sessions
      set page_id = p_page_id,
          system_id = coalesce(nullif(p_system_id, ''), 'pokerole'),
          status = 'setup',
          version = 0,
          state = p_state,
          created_by = v_user,
          created_at = now(),
          updated_at = now()
      where id = v_session.id
      returning * into v_session;
    else
      insert into public.game_engine_sessions (
        game_id, page_id, system_id, status, version, state, created_by
      ) values (
        p_game_id,
        p_page_id,
        coalesce(nullif(p_system_id, ''), 'pokerole'),
        'setup',
        0,
        p_state,
        v_user
      ) returning * into v_session;
    end if;

    insert into public.game_engine_events (
      session_id, game_id, version, actor_user_id, command, payload
    ) values (
      v_session.id,
      p_game_id,
      0,
      v_user,
      'start_session',
      jsonb_build_object(
        'pageId', p_page_id,
        'systemId', v_session.system_id,
        'participantCount', jsonb_array_length(p_state -> 'participants')
      )
    );

    return v_session;
  end;
  $$;

  create or replace function public.commit_game_engine_state(
    p_session_id uuid,
    p_expected_version bigint,
    p_command text,
    p_payload jsonb,
    p_next_state jsonb
  )
  returns public.game_engine_sessions
  language plpgsql
  security definer
  set search_path = public
  as $$
  declare
    v_user uuid := auth.uid();
    v_session public.game_engine_sessions;
    v_is_narrator boolean;
    v_current_owner text;
    v_target_owner text;
    v_turn_index integer;
    v_next_status text;
  begin
    if v_user is null then
      raise exception 'Authentication required' using errcode = '42501';
    end if;

    select * into v_session
    from public.game_engine_sessions
    where id = p_session_id
    for update;
    if not found then
      raise exception 'Engine session not found' using errcode = 'P0002';
    end if;

    v_is_narrator := public.is_game_narrator(v_session.game_id, v_user);
    if not v_is_narrator and not public.is_game_member(v_session.game_id, v_user) then
      raise exception 'You are not a member of this game' using errcode = '42501';
    end if;
    if v_session.version <> p_expected_version then
      raise exception 'Engine state changed; reload and try again' using errcode = '40001';
    end if;
    if p_command not in (
      'set_initiative', 'start_turns', 'record_action', 'advance_turn',
      'pause', 'resume', 'finish'
    ) then
      raise exception 'Unsupported engine command' using errcode = '22023';
    end if;
    if jsonb_typeof(p_next_state) <> 'object'
       or coalesce((p_next_state ->> 'schemaVersion')::integer, 0) <> 1
       or jsonb_typeof(p_next_state -> 'participants') <> 'array' then
      raise exception 'Invalid next engine state' using errcode = '22023';
    end if;

    v_turn_index := greatest(coalesce((v_session.state ->> 'turnIndex')::integer, 0), 0);
    v_current_owner := v_session.state #>> array['participants', v_turn_index::text, 'ownerId'];
    select participant ->> 'ownerId'
      into v_target_owner
    from jsonb_array_elements(v_session.state -> 'participants') participant
    where participant ->> 'id' = p_payload ->> 'participantId'
    limit 1;

    if not v_is_narrator then
      if p_command in ('set_initiative', 'record_action')
         and v_target_owner is distinct from v_user::text then
        raise exception 'You do not control this participant' using errcode = '42501';
      elsif p_command = 'advance_turn' and v_current_owner is distinct from v_user::text then
        raise exception 'You do not control the current turn' using errcode = '42501';
      elsif p_command not in ('set_initiative', 'record_action', 'advance_turn') then
        raise exception 'Only the narrator can use this command' using errcode = '42501';
      end if;
    end if;

    v_next_status := p_next_state ->> 'status';
    if v_next_status not in ('setup', 'running', 'paused', 'finished') then
      raise exception 'Invalid engine status' using errcode = '22023';
    end if;

    update public.game_engine_sessions
    set state = p_next_state,
        status = v_next_status,
        version = version + 1,
        updated_at = now()
    where id = p_session_id
    returning * into v_session;

    insert into public.game_engine_events (
      session_id, game_id, version, actor_user_id, command, payload
    ) values (
      v_session.id,
      v_session.game_id,
      v_session.version,
      v_user,
      p_command,
      coalesce(p_payload, '{}'::jsonb)
    );

    return v_session;
  end;
  $$;

  revoke all on function public.start_game_engine_session(uuid, uuid, text, jsonb) from public, anon;
  revoke all on function public.commit_game_engine_state(uuid, bigint, text, jsonb, jsonb) from public, anon;
  grant execute on function public.start_game_engine_session(uuid, uuid, text, jsonb) to authenticated;
  grant execute on function public.commit_game_engine_state(uuid, bigint, text, jsonb, jsonb) to authenticated;

  do $$
  begin
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'game_engine_sessions'
    ) then
      alter publication supabase_realtime add table public.game_engine_sessions;
    end if;
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'game_engine_events'
    ) then
      alter publication supabase_realtime add table public.game_engine_events;
    end if;
  end $$;

  alter table public.game_engine_sessions replica identity full;
  alter table public.game_engine_events replica identity full;
