ALTER TABLE public.species ADD COLUMN IF NOT EXISTS evolutions text[] NOT NULL DEFAULT '{}';

-- Seed evolutions from Pokérole 2.0 dataset
UPDATE public.species SET evolutions = ARRAY['Abomasnow (Mega Form)']::text[] WHERE name = 'Abomasnow';
UPDATE public.species SET evolutions = ARRAY['Kadabra']::text[] WHERE name = 'Abra';
UPDATE public.species SET evolutions = ARRAY['Absol (Mega Form)']::text[] WHERE name = 'Absol';
UPDATE public.species SET evolutions = ARRAY['Aegislash (Blade Form)']::text[] WHERE name = 'Aegislash';
UPDATE public.species SET evolutions = ARRAY['Aerodactyl (Mega Form)']::text[] WHERE name = 'Aerodactyl';
UPDATE public.species SET evolutions = ARRAY['Aggron (Mega Form)']::text[] WHERE name = 'Aggron';
UPDATE public.species SET evolutions = ARRAY['Ambipom']::text[] WHERE name = 'Aipom';
UPDATE public.species SET evolutions = ARRAY['Alakazam (Mega Form)']::text[] WHERE name = 'Alakazam';
UPDATE public.species SET evolutions = ARRAY['Altaria (Mega Form)']::text[] WHERE name = 'Altaria';
UPDATE public.species SET evolutions = ARRAY['Aurorus']::text[] WHERE name = 'Amaura';
UPDATE public.species SET evolutions = ARRAY['Ampharos (Mega Form)']::text[] WHERE name = 'Ampharos';
UPDATE public.species SET evolutions = ARRAY['Armaldo']::text[] WHERE name = 'Anorith';
UPDATE public.species SET evolutions = ARRAY['Flapple','Appletun']::text[] WHERE name = 'Applin';
UPDATE public.species SET evolutions = ARRAY['Archeops']::text[] WHERE name = 'Archen';
UPDATE public.species SET evolutions = ARRAY['Lairon']::text[] WHERE name = 'Aron';
UPDATE public.species SET evolutions = ARRAY['Barraskewda']::text[] WHERE name = 'Arrokuda';
UPDATE public.species SET evolutions = ARRAY['Audino (Mega Form)']::text[] WHERE name = 'Audino';
UPDATE public.species SET evolutions = ARRAY['Fraxure']::text[] WHERE name = 'Axew';
UPDATE public.species SET evolutions = ARRAY['Marill']::text[] WHERE name = 'Azurill';
UPDATE public.species SET evolutions = ARRAY['Shelgon']::text[] WHERE name = 'Bagon';
UPDATE public.species SET evolutions = ARRAY['Claydol']::text[] WHERE name = 'Baltoy';
UPDATE public.species SET evolutions = ARRAY['Banette (Mega Form)']::text[] WHERE name = 'Banette';
UPDATE public.species SET evolutions = ARRAY['Whiscash']::text[] WHERE name = 'Barboach';
UPDATE public.species SET evolutions = ARRAY['Meganium']::text[] WHERE name = 'Bayleef';
UPDATE public.species SET evolutions = ARRAY['Beedrill (Mega Form)']::text[] WHERE name = 'Beedrill';
UPDATE public.species SET evolutions = ARRAY['Metang']::text[] WHERE name = 'Beldum';
UPDATE public.species SET evolutions = ARRAY['Weepinbell']::text[] WHERE name = 'Bellsprout';
UPDATE public.species SET evolutions = ARRAY['Avalugg']::text[] WHERE name = 'Bergmite';
UPDATE public.species SET evolutions = ARRAY['Bibarel']::text[] WHERE name = 'Bidoof';
UPDATE public.species SET evolutions = ARRAY['Barbaracle']::text[] WHERE name = 'Binacle';
UPDATE public.species SET evolutions = ARRAY['Blastoise (Mega Form)']::text[] WHERE name = 'Blastoise';
UPDATE public.species SET evolutions = ARRAY['Blaziken (Mega Form)']::text[] WHERE name = 'Blaziken';
UPDATE public.species SET evolutions = ARRAY['Dottler']::text[] WHERE name = 'Blipbug';
UPDATE public.species SET evolutions = ARRAY['Zebstrika']::text[] WHERE name = 'Blitzle';
UPDATE public.species SET evolutions = ARRAY['Gigalith']::text[] WHERE name = 'Boldore';
UPDATE public.species SET evolutions = ARRAY['Sudowoodo']::text[] WHERE name = 'Bonsly';
UPDATE public.species SET evolutions = ARRAY['Steenee']::text[] WHERE name = 'Bounsweet';
UPDATE public.species SET evolutions = ARRAY['Delphox']::text[] WHERE name = 'Braixen';
UPDATE public.species SET evolutions = ARRAY['Primarina']::text[] WHERE name = 'Brionne';
UPDATE public.species SET evolutions = ARRAY['Bronzong']::text[] WHERE name = 'Bronzor';
UPDATE public.species SET evolutions = ARRAY['Roselia']::text[] WHERE name = 'Budew';
UPDATE public.species SET evolutions = ARRAY['Floatzel']::text[] WHERE name = 'Buizel';
UPDATE public.species SET evolutions = ARRAY['Ivysaur']::text[] WHERE name = 'Bulbasaur';
UPDATE public.species SET evolutions = ARRAY['Lopunny']::text[] WHERE name = 'Buneary';
UPDATE public.species SET evolutions = ARRAY['Diggersby']::text[] WHERE name = 'Bunnelby';
UPDATE public.species SET evolutions = ARRAY['Wormadam (Grass Form)','Wormadam (Steel Form)','Wormadam (Ground Form)','Mothim']::text[] WHERE name = 'Burmy';
UPDATE public.species SET evolutions = ARRAY['Cacturne']::text[] WHERE name = 'Cacnea';
UPDATE public.species SET evolutions = ARRAY['Camerupt (Mega Form)']::text[] WHERE name = 'Camerupt';
UPDATE public.species SET evolutions = ARRAY['Coalossal']::text[] WHERE name = 'Carkol';
UPDATE public.species SET evolutions = ARRAY['Sharpedo']::text[] WHERE name = 'Carvanha';
UPDATE public.species SET evolutions = ARRAY['Dustox']::text[] WHERE name = 'Cascoon';
UPDATE public.species SET evolutions = ARRAY['Metapod']::text[] WHERE name = 'Caterpie';
UPDATE public.species SET evolutions = ARRAY['Blissey']::text[] WHERE name = 'Chansey';
UPDATE public.species SET evolutions = ARRAY['Charizard (Mega Y Form)','Charizard (Mega X Form)']::text[] WHERE name = 'Charizard';
UPDATE public.species SET evolutions = ARRAY['Vikavolt']::text[] WHERE name = 'Charjabug';
UPDATE public.species SET evolutions = ARRAY['Charmeleon']::text[] WHERE name = 'Charmander';
UPDATE public.species SET evolutions = ARRAY['Charizard']::text[] WHERE name = 'Charmeleon';
UPDATE public.species SET evolutions = ARRAY['Cherrim']::text[] WHERE name = 'Cherubi';
UPDATE public.species SET evolutions = ARRAY['Quilladin']::text[] WHERE name = 'Chespin';
UPDATE public.species SET evolutions = ARRAY['Drednaw']::text[] WHERE name = 'Chewtle';
UPDATE public.species SET evolutions = ARRAY['Bayleef']::text[] WHERE name = 'Chikorita';
UPDATE public.species SET evolutions = ARRAY['Monferno']::text[] WHERE name = 'Chimchar';
UPDATE public.species SET evolutions = ARRAY['Lanturn']::text[] WHERE name = 'Chinchou';
UPDATE public.species SET evolutions = ARRAY['Chimecho']::text[] WHERE name = 'Chingling';
UPDATE public.species SET evolutions = ARRAY['Huntail','Gorebyss']::text[] WHERE name = 'Clamperl';
UPDATE public.species SET evolutions = ARRAY['Clawitzer']::text[] WHERE name = 'Clauncher';
UPDATE public.species SET evolutions = ARRAY['Clefable']::text[] WHERE name = 'Clefairy';
UPDATE public.species SET evolutions = ARRAY['Clefairy']::text[] WHERE name = 'Cleffa';
UPDATE public.species SET evolutions = ARRAY['Grapploct']::text[] WHERE name = 'Clobbopus';
UPDATE public.species SET evolutions = ARRAY['Vespiquen']::text[] WHERE name = 'Combee';
UPDATE public.species SET evolutions = ARRAY['Blaziken']::text[] WHERE name = 'Combusken';
UPDATE public.species SET evolutions = ARRAY['Crawdaunt']::text[] WHERE name = 'Corphish';
UPDATE public.species SET evolutions = ARRAY['Cursola']::text[] WHERE name = 'Corsola (Galarian Form)';
UPDATE public.species SET evolutions = ARRAY['Corviknight']::text[] WHERE name = 'Corvisquire';
UPDATE public.species SET evolutions = ARRAY['Solgaleo','Lunala']::text[] WHERE name = 'Cosmoem';
UPDATE public.species SET evolutions = ARRAY['Cosmoem']::text[] WHERE name = 'Cosmog';
UPDATE public.species SET evolutions = ARRAY['Whimsicott']::text[] WHERE name = 'Cottonee';
UPDATE public.species SET evolutions = ARRAY['Crabominable']::text[] WHERE name = 'Crabrawler';
UPDATE public.species SET evolutions = ARRAY['Rampardos']::text[] WHERE name = 'Cranidos';
UPDATE public.species SET evolutions = ARRAY['Toxicroak']::text[] WHERE name = 'Croagunk';
UPDATE public.species SET evolutions = ARRAY['Feraligatr']::text[] WHERE name = 'Croconaw';
UPDATE public.species SET evolutions = ARRAY['Beartic']::text[] WHERE name = 'Cubchoo';
UPDATE public.species SET evolutions = ARRAY['Marowak','Marowak (Alolan Form)']::text[] WHERE name = 'Cubone';
UPDATE public.species SET evolutions = ARRAY['Copperajah']::text[] WHERE name = 'Cufant';
UPDATE public.species SET evolutions = ARRAY['Ribombee']::text[] WHERE name = 'Cutiefly';
UPDATE public.species SET evolutions = ARRAY['Quilava']::text[] WHERE name = 'Cyndaquil';
UPDATE public.species SET evolutions = ARRAY['Darmanitan (Galarian Zen Form)']::text[] WHERE name = 'Darmanitan (Galarian Form)';
UPDATE public.species SET evolutions = ARRAY['Darmanitan (Zen Form)']::text[] WHERE name = 'Darmanitan';
UPDATE public.species SET evolutions = ARRAY['Decidueye']::text[] WHERE name = 'Dartrix';
UPDATE public.species SET evolutions = ARRAY['Darmanitan (Galarian Form)']::text[] WHERE name = 'Darumaka (Galarian Form)';
UPDATE public.species SET evolutions = ARRAY['Darmanitan']::text[] WHERE name = 'Darumaka';
UPDATE public.species SET evolutions = ARRAY['Sawsbuck']::text[] WHERE name = 'Deerling';
UPDATE public.species SET evolutions = ARRAY['Zweilous']::text[] WHERE name = 'Deino';
UPDATE public.species SET evolutions = ARRAY['Deoxys (Attack Form)','Deoxys (Defense Form)','Deoxys (Speed Form)']::text[] WHERE name = 'Deoxys';
UPDATE public.species SET evolutions = ARRAY['Samurott']::text[] WHERE name = 'Dewott';
UPDATE public.species SET evolutions = ARRAY['Araquanid']::text[] WHERE name = 'Dewpider';
UPDATE public.species SET evolutions = ARRAY['Diancie (Mega Form)']::text[] WHERE name = 'Diancie';
UPDATE public.species SET evolutions = ARRAY['Dugtrio (Alolan Form)']::text[] WHERE name = 'Diglett (Alolan Form)';
UPDATE public.species SET evolutions = ARRAY['Dugtrio']::text[] WHERE name = 'Diglett';
UPDATE public.species SET evolutions = ARRAY['Dodrio']::text[] WHERE name = 'Doduo';
UPDATE public.species SET evolutions = ARRAY['Orbeetle']::text[] WHERE name = 'Dottler';
UPDATE public.species SET evolutions = ARRAY['Aegislash']::text[] WHERE name = 'Doublade';
UPDATE public.species SET evolutions = ARRAY['Dragonite']::text[] WHERE name = 'Dragonair';
UPDATE public.species SET evolutions = ARRAY['Dragapult']::text[] WHERE name = 'Drakloak';
UPDATE public.species SET evolutions = ARRAY['Dragonair']::text[] WHERE name = 'Dratini';
UPDATE public.species SET evolutions = ARRAY['Drakloak']::text[] WHERE name = 'Dreepy';
UPDATE public.species SET evolutions = ARRAY['Drifblim']::text[] WHERE name = 'Drifloon';
UPDATE public.species SET evolutions = ARRAY['Vibrava']::text[] WHERE name = 'Trapinch';
UPDATE public.species SET evolutions = ARRAY['Flygon']::text[] WHERE name = 'Vibrava';
UPDATE public.species SET evolutions = ARRAY['Hippowdon']::text[] WHERE name = 'Hippopotas';
UPDATE public.species SET evolutions = ARRAY['Drowzee']::text[] WHERE name = 'Drowzee' AND false;
UPDATE public.species SET evolutions = ARRAY['Hypno']::text[] WHERE name = 'Drowzee';
UPDATE public.species SET evolutions = ARRAY['Druddigon (Mega Form)']::text[] WHERE name = 'Druddigon' AND false;
UPDATE public.species SET evolutions = ARRAY['Linoone']::text[] WHERE name = 'Zigzagoon';
UPDATE public.species SET evolutions = ARRAY['Mightyena']::text[] WHERE name = 'Poochyena';
UPDATE public.species SET evolutions = ARRAY['Pelipper']::text[] WHERE name = 'Wingull';
UPDATE public.species SET evolutions = ARRAY['Ninjask','Shedinja']::text[] WHERE name = 'Nincada';
UPDATE public.species SET evolutions = ARRAY['Loudred']::text[] WHERE name = 'Whismur';
UPDATE public.species SET evolutions = ARRAY['Exploud']::text[] WHERE name = 'Loudred';
UPDATE public.species SET evolutions = ARRAY['Mawile (Mega Form)']::text[] WHERE name = 'Mawile';
UPDATE public.species SET evolutions = ARRAY['Lairon']::text[] WHERE name = 'Aron' AND false;
UPDATE public.species SET evolutions = ARRAY['Aggron']::text[] WHERE name = 'Lairon';
UPDATE public.species SET evolutions = ARRAY['Medicham']::text[] WHERE name = 'Meditite';
UPDATE public.species SET evolutions = ARRAY['Electrode']::text[] WHERE name = 'Voltorb';
UPDATE public.species SET evolutions = ARRAY['Marowak']::text[] WHERE name = 'Cubone' AND false;
UPDATE public.species SET evolutions = ARRAY['Hitmonlee','Hitmonchan','Hitmontop']::text[] WHERE name = 'Tyrogue';
UPDATE public.species SET evolutions = ARRAY['Pichu']::text[] WHERE name = 'Pichu' AND false;
UPDATE public.species SET evolutions = ARRAY['Pikachu']::text[] WHERE name = 'Pichu';
UPDATE public.species SET evolutions = ARRAY['Raichu','Raichu (Alolan Form)']::text[] WHERE name = 'Pikachu';
UPDATE public.species SET evolutions = ARRAY['Wartortle']::text[] WHERE name = 'Squirtle';
UPDATE public.species SET evolutions = ARRAY['Blastoise']::text[] WHERE name = 'Wartortle';
UPDATE public.species SET evolutions = ARRAY['Ivysaur']::text[] WHERE name = 'Bulbasaur' AND false;
UPDATE public.species SET evolutions = ARRAY['Venusaur']::text[] WHERE name = 'Ivysaur';
UPDATE public.species SET evolutions = ARRAY['Venusaur (Mega Form)']::text[] WHERE name = 'Venusaur';
UPDATE public.species SET evolutions = ARRAY['Charmeleon']::text[] WHERE name = 'Charmander' AND false;
UPDATE public.species SET evolutions = ARRAY['Charizard']::text[] WHERE name = 'Charmeleon' AND false;
UPDATE public.species SET evolutions = ARRAY['Vaporeon','Jolteon','Flareon','Espeon','Umbreon','Leafeon','Glaceon','Sylveon']::text[] WHERE name = 'Eevee';
UPDATE public.species SET evolutions = ARRAY['Pidgeotto']::text[] WHERE name = 'Pidgey';
UPDATE public.species SET evolutions = ARRAY['Pidgeot']::text[] WHERE name = 'Pidgeotto';
UPDATE public.species SET evolutions = ARRAY['Pidgeot (Mega Form)']::text[] WHERE name = 'Pidgeot';
UPDATE public.species SET evolutions = ARRAY['Metapod']::text[] WHERE name = 'Caterpie' AND false;
UPDATE public.species SET evolutions = ARRAY['Butterfree']::text[] WHERE name = 'Metapod';
UPDATE public.species SET evolutions = ARRAY['Kakuna']::text[] WHERE name = 'Weedle';
UPDATE public.species SET evolutions = ARRAY['Beedrill']::text[] WHERE name = 'Kakuna';