-- LANCER Phase 1: canonical entities, campaign state, permissions and events.
-- This is additive and does not alter Pokemon or T20 data.

create table if not exists public.lancer_campaigns (
  game_id uuid primary key references public.games(id) on delete cascade,
  rules_version text not null default 'core',
  auto_apply_damage boolean not null default true,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lancer_campaign_settings_object check (jsonb_typeof(settings) = 'object')
);

create table if not exists public.lancer_entities (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games(id) on delete cascade,
  owner_id uuid references auth.users(id) on delete set null,
  entity_type text not null
    check (entity_type in ('pilot', 'mech', 'npc', 'object', 'deployable')),
  name text not null check (char_length(btrim(name)) between 1 and 120),
  callsign text check (callsign is null or char_length(btrim(callsign)) <= 120),
  source_type text not null default 'campaign'
    check (source_type in ('core', 'lcp', 'homebrew', 'campaign')),
  source_id text,
  current_state jsonb not null,
  build_state jsonb not null,
  revision bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lancer_entity_current_state_object check (jsonb_typeof(current_state) = 'object'),
  constraint lancer_entity_build_state_object check (jsonb_typeof(build_state) = 'object'),
  constraint lancer_entity_state_version check (
    coalesce((current_state ->> 'schemaVersion')::integer, 0) = 1
    and current_state ->> 'kind' = entity_type
  ),
  constraint lancer_entity_build_version check (
    coalesce((build_state ->> 'schemaVersion')::integer, 0) = 1
  )
);

create index if not exists lancer_entities_game_type_idx
  on public.lancer_entities(game_id, entity_type, created_at);
create index if not exists lancer_entities_owner_idx
  on public.lancer_entities(owner_id) where owner_id is not null;

create table if not exists public.lancer_entity_permissions (
  entity_id uuid not null references public.lancer_entities(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  can_view boolean not null default true,
  can_edit boolean not null default false,
  can_control boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (entity_id, user_id)
);

create table if not exists public.lancer_combat_transactions (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  action_type text not null,
  action_payload jsonb not null default '{}'::jsonb,
  before_state jsonb not null,
  after_state jsonb not null,
  generated_events jsonb not null default '[]'::jsonb,
  reversed_by uuid references public.lancer_combat_transactions(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint lancer_transaction_payload_object check (jsonb_typeof(action_payload) = 'object'),
  constraint lancer_transaction_before_object check (jsonb_typeof(before_state) = 'object'),
  constraint lancer_transaction_after_object check (jsonb_typeof(after_state) = 'object'),
  constraint lancer_transaction_events_array check (jsonb_typeof(generated_events) = 'array')
);

create index if not exists lancer_transactions_game_created_idx
  on public.lancer_combat_transactions(game_id, created_at desc);

create table if not exists public.lancer_game_events (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  entity_id uuid references public.lancer_entities(id) on delete set null,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  transaction_id uuid references public.lancer_combat_transactions(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint lancer_event_payload_object check (jsonb_typeof(payload) = 'object')
);

create index if not exists lancer_events_game_created_idx
  on public.lancer_game_events(game_id, created_at desc);
create index if not exists lancer_events_entity_created_idx
  on public.lancer_game_events(entity_id, created_at desc) where entity_id is not null;

alter table public.lancer_campaigns enable row level security;
alter table public.lancer_entities enable row level security;
alter table public.lancer_entity_permissions enable row level security;
alter table public.lancer_combat_transactions enable row level security;
alter table public.lancer_game_events enable row level security;

create or replace function public.can_control_lancer_entity(
  p_entity_id uuid,
  p_user_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.lancer_entities entity
    where entity.id = p_entity_id
      and (
        public.is_game_narrator(entity.game_id, p_user_id)
        or entity.owner_id = p_user_id
        or exists (
          select 1
          from public.lancer_entity_permissions permission
          where permission.entity_id = entity.id
            and permission.user_id = p_user_id
            and (permission.can_edit or permission.can_control)
        )
      )
  );
$$;

revoke all on function public.can_control_lancer_entity(uuid, uuid) from public, anon;
grant execute on function public.can_control_lancer_entity(uuid, uuid) to authenticated;

drop policy if exists "members view lancer campaign" on public.lancer_campaigns;
create policy "members view lancer campaign"
  on public.lancer_campaigns for select to authenticated
  using (
    public.is_game_member(game_id, auth.uid())
    or public.is_game_narrator(game_id, auth.uid())
  );

drop policy if exists "narrator manages lancer campaign" on public.lancer_campaigns;
create policy "narrator manages lancer campaign"
  on public.lancer_campaigns for all to authenticated
  using (public.is_game_narrator(game_id, auth.uid()))
  with check (public.is_game_narrator(game_id, auth.uid()));

drop policy if exists "members view lancer entities" on public.lancer_entities;
create policy "members view lancer entities"
  on public.lancer_entities for select to authenticated
  using (
    public.is_game_member(game_id, auth.uid())
    or public.is_game_narrator(game_id, auth.uid())
  );

drop policy if exists "controllers manage lancer entities" on public.lancer_entities;
create policy "controllers manage lancer entities"
  on public.lancer_entities for update to authenticated
  using (public.can_control_lancer_entity(id, auth.uid()))
  with check (public.can_control_lancer_entity(id, auth.uid()));

drop policy if exists "controllers delete lancer entities" on public.lancer_entities;
create policy "controllers delete lancer entities"
  on public.lancer_entities for delete to authenticated
  using (public.can_control_lancer_entity(id, auth.uid()));

drop policy if exists "authorized users view lancer permissions" on public.lancer_entity_permissions;
create policy "authorized users view lancer permissions"
  on public.lancer_entity_permissions for select to authenticated
  using (
    user_id = auth.uid()
    or exists (
      select 1 from public.lancer_entities entity
      where entity.id = entity_id
        and (
          entity.owner_id = auth.uid()
          or public.is_game_narrator(entity.game_id, auth.uid())
        )
    )
  );

drop policy if exists "owners manage lancer permissions" on public.lancer_entity_permissions;
create policy "owners manage lancer permissions"
  on public.lancer_entity_permissions for all to authenticated
  using (
    exists (
      select 1 from public.lancer_entities entity
      where entity.id = entity_id
        and (
          entity.owner_id = auth.uid()
          or public.is_game_narrator(entity.game_id, auth.uid())
        )
    )
  )
  with check (
    exists (
      select 1 from public.lancer_entities entity
      where entity.id = entity_id
        and (
          entity.owner_id = auth.uid()
          or public.is_game_narrator(entity.game_id, auth.uid())
        )
    )
  );

drop policy if exists "members view lancer transactions" on public.lancer_combat_transactions;
create policy "members view lancer transactions"
  on public.lancer_combat_transactions for select to authenticated
  using (
    public.is_game_member(game_id, auth.uid())
    or public.is_game_narrator(game_id, auth.uid())
  );

drop policy if exists "members view lancer events" on public.lancer_game_events;
create policy "members view lancer events"
  on public.lancer_game_events for select to authenticated
  using (
    public.is_game_member(game_id, auth.uid())
    or public.is_game_narrator(game_id, auth.uid())
  );

create or replace function public.ensure_lancer_campaign()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.system = 'lancer' then
    insert into public.lancer_campaigns (game_id)
    values (new.id)
    on conflict (game_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists ensure_lancer_campaign_after_game_write on public.games;
create trigger ensure_lancer_campaign_after_game_write
after insert or update of system on public.games
for each row execute function public.ensure_lancer_campaign();

revoke all on function public.ensure_lancer_campaign() from public, anon, authenticated;

insert into public.lancer_campaigns (game_id)
select game.id
from public.games game
where game.system = 'lancer'
on conflict (game_id) do nothing;

create or replace function public.create_lancer_entity(
  p_game_id uuid,
  p_entity_type text,
  p_name text,
  p_callsign text,
  p_owner_id uuid,
  p_current_state jsonb,
  p_build_state jsonb
)
returns public.lancer_entities
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_owner uuid := coalesce(p_owner_id, v_user);
  v_entity public.lancer_entities;
begin
  if v_user is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if not public.is_game_member(p_game_id, v_user)
     and not public.is_game_narrator(p_game_id, v_user) then
    raise exception 'You are not a member of this campaign' using errcode = '42501';
  end if;
  if not exists (select 1 from public.games where id = p_game_id and system = 'lancer') then
    raise exception 'This campaign does not use LANCER' using errcode = '22023';
  end if;
  if p_entity_type not in ('pilot', 'mech', 'npc', 'object', 'deployable') then
    raise exception 'Invalid LANCER entity type' using errcode = '22023';
  end if;
  if btrim(coalesce(p_name, '')) = '' then
    raise exception 'Entity name is required' using errcode = '22023';
  end if;
  if not public.is_game_narrator(p_game_id, v_user) then
    if v_owner is distinct from v_user then
      raise exception 'Players can only create their own entities' using errcode = '42501';
    end if;
    if p_entity_type in ('npc', 'object', 'deployable') then
      raise exception 'Only the GM can create this entity type' using errcode = '42501';
    end if;
  end if;
  if v_owner is not null and not public.is_game_member(p_game_id, v_owner)
     and not public.is_game_narrator(p_game_id, v_owner) then
    raise exception 'Entity owner is not a campaign member' using errcode = '23503';
  end if;
  if jsonb_typeof(p_current_state) <> 'object'
     or coalesce((p_current_state ->> 'schemaVersion')::integer, 0) <> 1
     or p_current_state ->> 'kind' <> p_entity_type then
    raise exception 'Invalid canonical entity state' using errcode = '22023';
  end if;
  if jsonb_typeof(p_build_state) <> 'object'
     or coalesce((p_build_state ->> 'schemaVersion')::integer, 0) <> 1 then
    raise exception 'Invalid build state' using errcode = '22023';
  end if;

  insert into public.lancer_entities (
    game_id, owner_id, entity_type, name, callsign, current_state, build_state
  ) values (
    p_game_id,
    v_owner,
    p_entity_type,
    btrim(p_name),
    nullif(btrim(coalesce(p_callsign, '')), ''),
    p_current_state,
    p_build_state
  ) returning * into v_entity;

  if v_owner is not null then
    insert into public.lancer_entity_permissions (
      entity_id, user_id, can_view, can_edit, can_control
    ) values (v_entity.id, v_owner, true, true, true)
    on conflict (entity_id, user_id) do update
      set can_view = true, can_edit = true, can_control = true, updated_at = now();
  end if;

  insert into public.lancer_game_events (
    game_id, entity_id, actor_user_id, event_type, payload
  ) values (
    p_game_id,
    v_entity.id,
    v_user,
    'entity_created',
    jsonb_build_object(
      'entityType', p_entity_type,
      'name', v_entity.name,
      'callsign', v_entity.callsign,
      'revision', v_entity.revision
    )
  );

  return v_entity;
end;
$$;

create or replace function public.commit_lancer_entity_state(
  p_entity_id uuid,
  p_expected_revision bigint,
  p_action_type text,
  p_action_payload jsonb,
  p_next_state jsonb,
  p_generated_events jsonb default '[]'::jsonb
)
returns public.lancer_entities
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_before public.lancer_entities;
  v_after public.lancer_entities;
  v_transaction_id uuid;
  v_event jsonb;
begin
  if v_user is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select * into v_before
  from public.lancer_entities
  where id = p_entity_id
  for update;
  if not found then
    raise exception 'LANCER entity not found' using errcode = 'P0002';
  end if;
  if not public.can_control_lancer_entity(p_entity_id, v_user) then
    raise exception 'You do not control this entity' using errcode = '42501';
  end if;
  if v_before.revision <> p_expected_revision then
    raise exception 'Entity changed; reload and try again' using errcode = '40001';
  end if;
  if btrim(coalesce(p_action_type, '')) = '' then
    raise exception 'Action type is required' using errcode = '22023';
  end if;
  if jsonb_typeof(coalesce(p_action_payload, '{}'::jsonb)) <> 'object'
     or jsonb_typeof(coalesce(p_generated_events, '[]'::jsonb)) <> 'array' then
    raise exception 'Invalid action payload or generated events' using errcode = '22023';
  end if;
  if jsonb_typeof(p_next_state) <> 'object'
     or coalesce((p_next_state ->> 'schemaVersion')::integer, 0) <> 1
     or p_next_state ->> 'kind' <> v_before.entity_type then
    raise exception 'Invalid canonical entity state' using errcode = '22023';
  end if;

  insert into public.lancer_combat_transactions (
    game_id, actor_user_id, action_type, action_payload,
    before_state, after_state, generated_events
  ) values (
    v_before.game_id,
    v_user,
    p_action_type,
    coalesce(p_action_payload, '{}'::jsonb),
    jsonb_build_object(
      'entityId', v_before.id,
      'revision', v_before.revision,
      'state', v_before.current_state
    ),
    jsonb_build_object(
      'entityId', v_before.id,
      'revision', v_before.revision + 1,
      'state', p_next_state
    ),
    coalesce(p_generated_events, '[]'::jsonb)
  ) returning id into v_transaction_id;

  update public.lancer_entities
  set current_state = p_next_state,
      revision = revision + 1,
      updated_at = now()
  where id = p_entity_id
  returning * into v_after;

  insert into public.lancer_game_events (
    game_id, entity_id, actor_user_id, transaction_id, event_type, payload
  ) values (
    v_after.game_id,
    v_after.id,
    v_user,
    v_transaction_id,
    p_action_type,
    coalesce(p_action_payload, '{}'::jsonb) || jsonb_build_object('revision', v_after.revision)
  );

  for v_event in
    select value from jsonb_array_elements(coalesce(p_generated_events, '[]'::jsonb))
  loop
    insert into public.lancer_game_events (
      game_id, entity_id, actor_user_id, transaction_id, event_type, payload
    ) values (
      v_after.game_id,
      coalesce(nullif(v_event ->> 'entityId', '')::uuid, v_after.id),
      v_user,
      v_transaction_id,
      coalesce(nullif(v_event ->> 'type', ''), 'state_changed'),
      coalesce(v_event -> 'payload', '{}'::jsonb)
    );
  end loop;

  return v_after;
end;
$$;

revoke all on function public.create_lancer_entity(uuid, text, text, text, uuid, jsonb, jsonb)
  from public, anon;
revoke all on function public.commit_lancer_entity_state(uuid, bigint, text, jsonb, jsonb, jsonb)
  from public, anon;
grant execute on function public.create_lancer_entity(uuid, text, text, text, uuid, jsonb, jsonb)
  to authenticated;
grant execute on function public.commit_lancer_entity_state(uuid, bigint, text, jsonb, jsonb, jsonb)
  to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'lancer_entities'
  ) then
    alter publication supabase_realtime add table public.lancer_entities;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'lancer_game_events'
  ) then
    alter publication supabase_realtime add table public.lancer_game_events;
  end if;
end $$;

alter table public.lancer_entities replica identity full;
alter table public.lancer_game_events replica identity full;
