-- The legacy PokéRole import stored Bug as Dark for species released before
-- Paldea. Replace only the known affected species so legitimate Dark types
-- (including Bug/Dark species such as Lokix) remain unchanged.
with bug_species(name) as (
  values
    ('Caterpie'),
    ('Metapod'),
    ('Butterfree'),
    ('Weedle'),
    ('Kakuna'),
    ('Beedrill'),
    ('Beedrill (Mega Form)'),
    ('Paras'),
    ('Parasect'),
    ('Venonat'),
    ('Venomoth'),
    ('Scyther'),
    ('Pinsir'),
    ('Pinsir (Mega Form)'),
    ('Ledyba'),
    ('Ledian'),
    ('Spinarak'),
    ('Ariados'),
    ('Yanma'),
    ('Pineco'),
    ('Forretress'),
    ('Scizor'),
    ('Scizor (Mega Form)'),
    ('Shuckle'),
    ('Heracross'),
    ('Heracross (Mega Form)'),
    ('Wurmple'),
    ('Silcoon'),
    ('Beautifly'),
    ('Cascoon'),
    ('Dustox'),
    ('Surskit'),
    ('Masquerain'),
    ('Nincada'),
    ('Ninjask'),
    ('Shedinja'),
    ('Volbeat'),
    ('Illumise'),
    ('Anorith'),
    ('Armaldo'),
    ('Kricketot'),
    ('Kricketune'),
    ('Burmy'),
    ('Wormadam (Grass Form)'),
    ('Wormadam (Ground Form)'),
    ('Wormadam (Steel Form)'),
    ('Mothim'),
    ('Combee'),
    ('Vespiquen'),
    ('Skorupi'),
    ('Yanmega'),
    ('Sewaddle'),
    ('Swadloon'),
    ('Leavanny'),
    ('Venipede'),
    ('Whirlipede'),
    ('Scolipede'),
    ('Dwebble'),
    ('Crustle'),
    ('Karrablast'),
    ('Escavalier'),
    ('Joltik'),
    ('Galvantula'),
    ('Shelmet'),
    ('Accelgor'),
    ('Durant'),
    ('Larvesta'),
    ('Volcarona'),
    ('Genesect'),
    ('Scatterbug'),
    ('Spewpa'),
    ('Vivillon'),
    ('Grubbin'),
    ('Charjabug'),
    ('Vikavolt'),
    ('Cutiefly'),
    ('Ribombee'),
    ('Dewpider'),
    ('Araquanid'),
    ('Wimpod'),
    ('Golisopod'),
    ('Buzzwole'),
    ('Pheromosa'),
    ('Blipbug'),
    ('Dottler'),
    ('Orbeetle'),
    ('Sizzlipede'),
    ('Centiskorch'),
    ('Snom'),
    ('Frosmoth')
)
update public.species as species
set types = array_replace(
  species.types,
  'dark'::public.pokemon_type,
  'bug'::public.pokemon_type
)
from bug_species
where species.name = bug_species.name
  and 'dark'::public.pokemon_type = any(species.types)
  and not ('bug'::public.pokemon_type = any(species.types));
